import {expect,type Page} from '@playwright/test';
export const fixedTime=new Date('2026-10-07T10:00:00Z');
export async function boot(page:Page){await page.clock.setFixedTime(fixedTime);await page.goto('/');await expect(page.getByTestId('daily-quote')).toBeVisible();await page.evaluate(()=>navigator.serviceWorker.ready);await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);}
export async function tab(page:Page,name:string){await page.getByRole('navigation').getByRole('button',{name,exact:true}).click();}
export async function weigh(page:Page,value:string){await tab(page,'Today');await page.locator('.task').filter({hasText:'Weight'}).click();await page.getByLabel('Weight in kilograms').fill(value);await page.getByRole('button',{name:'Save weight',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);}
export async function state(page:Page){return page.evaluate(()=>new Promise<any>((resolve,reject)=>{const request=indexedDB.open('daily-os',1);request.onsuccess=()=>{const db=request.result,tx=db.transaction('state','readonly'),r=tx.objectStore('state').get('main');r.onsuccess=()=>resolve(r.result);tx.oncomplete=()=>db.close();tx.onerror=()=>reject(tx.error);};request.onerror=()=>reject(request.error);}));}
export async function rest(page:Page){await tab(page,'Today');await page.getByRole('button',{name:'Mark as Rest Day',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Rest Day',exact:true}).click();await expect(page.locator('.hero-label')).toHaveText('REST DAY');}
export async function allDone(page:Page){await weigh(page,'76.7');while(await page.locator('.task[aria-pressed="false"]').count()){await page.locator('.task[aria-pressed="false"]').first().click();await expect(page.locator('.task:disabled')).toHaveCount(0);}await expect(page.locator('.hero-label')).toHaveText('DAY COMPLETE ✓');}
export async function noOverflow(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const nav=await page.getByRole('navigation').boundingBox();expect(nav?.width).toBeLessThanOrEqual(page.viewportSize()!.width);}
