import {test,expect} from '@playwright/test';
import {testServer} from '../scripts/test-server.mjs';
import {defaults,ensureDays,saveWeight,setCompletion,exportBackup} from '../src/model';
import {fixedTime,tab,state,weigh} from './helpers';
test('real v1.2 shell → v1.4 update retains IndexedDB, old assets and offline use',async({page,context})=>{
 const server=await testServer('.test-fixtures/v12');
 try{await page.clock.setFixedTime(fixedTime);await page.goto(server.url);await page.evaluate(()=>navigator.serviceWorker.ready);await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);
 const legacy=defaults('2026-10-05');ensureDays(legacy,'2026-10-07');for(const date of Object.keys(legacy.days)){saveWeight(legacy,76.8,date);for(const t of legacy.days[date].taskSnapshot.filter(t=>t.type==='checkbox'))setCompletion(legacy,t.id,true,date);}legacy.tasks.find(t=>t.id==='omega')!.title='Daily omega';const backup={...JSON.parse(exportBackup(legacy)),version:2};await tab(page,'Settings');await page.locator('input[type="file"]').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.getByRole('dialog').getByRole('button',{name:'Import',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await tab(page,'Today');await expect(page.locator('.streak-strip')).toContainText('3 day streak');await weigh(page,'76.8');await tab(page,'Settings');await page.getByLabel('Appearance').selectOption('dark');await expect(page.locator('.footer-note')).toContainText('1.2.0');const before=await state(page);const oldAsset=await page.locator('script[type="module"]').getAttribute('src');
 server.setRoot('dist');await page.evaluate(async()=>{const reg=await navigator.serviceWorker.getRegistration();await reg!.update();});await expect.poll(()=>page.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();return r?.waiting?.state})).toBe('installed');await expect(page.getByText(/Update available/)).toBeVisible();await page.getByRole('button',{name:'Reload',exact:true}).click();await expect(page.getByTestId('daily-quote')).toBeVisible();{const after=await state(page);for(const key of ['tasks','days','measurements','settings','startedOn'])expect(after[key]).toEqual(before[key]);expect(after.money).toEqual({currency:'PLN',startingBalanceMinor:null,transactions:[]});}
 await tab(page,'Settings');await expect(page.locator('.footer-note')).toContainText('1.4.0');await tab(page,'History');await expect(page.locator('.history-row').first()).toContainText('76.8 kg');await tab(page,'Progress');await expect(page.locator('.weight-chart')).toBeVisible();await tab(page,'Today');await expect(page.locator('.streak-strip')).toContainText('3 day streak');await expect(page.locator('.task').filter({hasText:'Omega-3'})).toHaveAttribute('aria-pressed','true');
 const cacheState=await page.evaluate(async old=>{const keys=(await caches.keys()).filter(k=>k.startsWith('daily-os-'));return {keys,oldAssetCached:!!(await caches.match(old!))};},oldAsset);expect(cacheState.keys).toHaveLength(1);expect(cacheState.oldAssetCached).toBe(true);
 await context.setOffline(true);await page.reload();await expect(page.getByTestId('daily-quote')).toBeVisible();{const after=await state(page);for(const key of ['tasks','days','measurements','settings','startedOn'])expect(after[key]).toEqual(before[key]);expect(after.money).toEqual({currency:'PLN',startingBalanceMinor:null,transactions:[]});}
 }finally{await server.close();}
});
