export type Period = 'Morning' | 'Afternoon' | 'Evening' | 'Anytime';
export interface Task { id: string; title: string; period: Period; daysOfWeek: number[]; enabled: boolean; type: 'checkbox' | 'weight'; role?: 'gym' }
export interface DailyRecord { date: string; completedTaskIds: string[]; taskSnapshot: Task[]; completionPercent: number }
export interface Measurement { date: string; kind: 'weight'; value: number; unit: 'kg' }
export interface State { schemaVersion: 1; startedOn: string; tasks: Task[]; days: Record<string, DailyRecord>; measurements: Measurement[]; settings: { timezone: 'Europe/Warsaw'; weightUnit: 'kg'; theme: 'system' | 'light' | 'dark' } }
export const weekLabels = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
export function localDate(now = new Date()) { const p = new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Warsaw',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now); return `${p.find(x=>x.type==='year')!.value}-${p.find(x=>x.type==='month')!.value}-${p.find(x=>x.type==='day')!.value}`; }
export function shiftDate(date:string, n:number) { const d = new Date(date+'T12:00:00Z'); d.setUTCDate(d.getUTCDate()+n); return d.toISOString().slice(0,10); }
export function weekday(date:string) { return (new Date(date+'T12:00:00Z').getUTCDay()+6)%7; }
export function displayDate(date:string, opts:Intl.DateTimeFormatOptions = {month:'long',day:'numeric'}) { return new Intl.DateTimeFormat('en-US',{...opts,timeZone:'UTC'}).format(new Date(date+'T12:00:00Z')); }
const every = [0,1,2,3,4,5,6];
export function defaults(date=localDate()):State { const tasks:Task[] = [
 {id:'face-am',title:'Wash face',period:'Morning',daysOfWeek:every,enabled:true,type:'checkbox'},
 {id:'weight',title:'Weight',period:'Morning',daysOfWeek:every,enabled:true,type:'weight'},
 {id:'omega',title:'Omega-3',period:'Morning',daysOfWeek:every,enabled:true,type:'checkbox'},
 {id:'vitamin-d',title:'Vitamin D',period:'Morning',daysOfWeek:every,enabled:true,type:'checkbox'},
 {id:'zinc',title:'Zinc',period:'Afternoon',daysOfWeek:every,enabled:true,type:'checkbox'},
 {id:'face-pm',title:'Wash face',period:'Evening',daysOfWeek:every,enabled:true,type:'checkbox'},
 {id:'magnesium',title:'Magnesium',period:'Evening',daysOfWeek:every,enabled:true,type:'checkbox'},
 {id:'gym',title:'Gym',period:'Anytime',daysOfWeek:[1,3,5],enabled:true,type:'checkbox',role:'gym'}];
 return ensureDays({schemaVersion:1,startedOn:date,tasks,days:{},measurements:[],settings:{timezone:'Europe/Warsaw',weightUnit:'kg',theme:'system'}},date); }
export function tasksOn(tasks:Task[],date:string) { return tasks.filter(t=>t.enabled && t.daysOfWeek.includes(weekday(date))).map(t=>({...t,daysOfWeek:[...t.daysOfWeek]})); }
export function ensureDays(s:State,date=localDate()):State { const latest = Object.keys(s.days).sort().at(-1); let next = latest ? shiftDate(latest,1) : s.startedOn; while(next<=date) { s.days[next]={date:next,completedTaskIds:[],taskSnapshot:tasksOn(s.tasks,next),completionPercent:0}; next=shiftDate(next,1); } return s; }
export function percent(r:DailyRecord) { return r.taskSnapshot.length ? Math.round(r.completedTaskIds.length/r.taskSnapshot.length*100) : 0; }
export function isComplete(r?:DailyRecord) { return !!r && r.taskSnapshot.length>0 && r.completedTaskIds.length===r.taskSnapshot.length; }
export function toggle(s:State,id:string,date=localDate()) { ensureDays(s,date); const r=s.days[date]; const task=r?.taskSnapshot.find(t=>t.id===id); if(!task || task.type==='weight') throw new Error('Task not available today.'); r.completedTaskIds=r.completedTaskIds.includes(id)?r.completedTaskIds.filter(x=>x!==id):[...r.completedTaskIds,id]; r.completionPercent=percent(r); return s; }
export function saveWeight(s:State,value:number,date=localDate()) { if(!Number.isFinite(value)||value<1||value>500) throw new Error('Enter a weight between 1 and 500 kg.'); ensureDays(s,date); value=Math.round(value*100)/100; s.measurements=s.measurements.filter(m=>m.date!==date||m.kind!=='weight'); s.measurements.push({date,kind:'weight',value,unit:'kg'}); s.measurements.sort((a,b)=>a.date.localeCompare(b.date)); const r=s.days[date]; for(const t of r.taskSnapshot.filter(t=>t.type==='weight')) if(!r.completedTaskIds.includes(t.id)) r.completedTaskIds.push(t.id); r.completionPercent=percent(r); return s; }
export function weightOn(s:State,date:string) { return s.measurements.find(m=>m.date===date&&m.kind==='weight')?.value; }
export function streaks(s:State,today=localDate()) { let best=0,run=0,previous=''; for(const date of Object.keys(s.days).filter(d=>d<=today).sort()) { const r=s.days[date]; run=isComplete(r)?(previous&&shiftDate(previous,1)===date?run+1:1):0; best=Math.max(best,run); previous=date; } let date=isComplete(s.days[today])?today:shiftDate(today,-1); let current=0; while(isComplete(s.days[date])) {current++;date=shiftDate(date,-1);} return {current,best}; }
export function weekStats(s:State,today=localDate()) { const monday=shiftDate(today,-weekday(today)); const dates=Array.from({length:7},(_,i)=>shiftDate(monday,i)); const elapsed=dates.filter(d=>d<=today); let done=0,total=0; for(const d of elapsed){ const r=s.days[d]; if(r){done+=r.completedTaskIds.length;total+=r.taskSnapshot.length;} } return {dates,percent:total?Math.round(done/total*100):0,completed:dates.filter(d=>isComplete(s.days[d])).length}; }
export function weightStats(s:State,today=localDate()) { const weights=s.measurements.filter(m=>m.kind==='weight'&&m.date<=today).sort((a,b)=>a.date.localeCompare(b.date)); const latest=weights.at(-1); const recent=weights.filter(m=>m.date>=shiftDate(today,-6)); const change=(old:number|undefined)=>latest&&old!==undefined?Math.round((latest.value-old)*100)/100:undefined; return {weights,latest,average:recent.length?recent.reduce((n,m)=>n+m.value,0)/recent.length:undefined,yesterday:change(weightOn(s,shiftDate(today,-1))),sevenDays:change(weightOn(s,shiftDate(today,-7))),first:change(weights[0]?.value)}; }
const validDate=(v:unknown):v is string=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&v>='2000-01-01'&&v<='2100-12-31'&&Number.isFinite(Date.parse(v+'T12:00:00Z'))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v;
function validTask(t:any):t is Task {return t&&typeof t.id==='string'&&/^[a-zA-Z0-9_-]{1,80}$/.test(t.id)&&typeof t.title==='string'&&t.title.trim().length>0&&t.title.length<=80&&['Morning','Afternoon','Evening','Anytime'].includes(t.period)&&Array.isArray(t.daysOfWeek)&&t.daysOfWeek.length>0&&t.daysOfWeek.length<=7&&new Set(t.daysOfWeek).size===t.daysOfWeek.length&&t.daysOfWeek.every((d:unknown)=>Number.isInteger(d)&&Number(d)>=0&&Number(d)<=6)&&typeof t.enabled==='boolean'&&['checkbox','weight'].includes(t.type)&&(t.role===undefined||(t.role==='gym'&&t.type==='checkbox'));}
function taskList(ts:any):ts is Task[]{ return Array.isArray(ts)&&ts.length<=100&&ts.every(validTask)&&new Set(ts.map(t=>t.id)).size===ts.length&&ts.filter(t=>t.role==='gym').length<=1; }
export function validateBackup(value:unknown):State { const raw=value as any; const s=raw?.app==='DAILY OS'?raw.data:raw;
 if(!s||s.schemaVersion!==1||!validDate(s.startedOn)||!taskList(s.tasks)||!s.days||typeof s.days!=='object'||Array.isArray(s.days)||!Array.isArray(s.measurements)||s.measurements.length>40000||!s.settings||s.settings.timezone!=='Europe/Warsaw'||s.settings.weightUnit!=='kg'||!['system','light','dark'].includes(s.settings.theme)) throw new Error('This is not a valid DAILY OS v1 backup.');
 const entries=Object.entries(s.days); if(entries.length>40000) throw new Error('Backup is too large.');
 for(const [date,rawRecord] of entries){const r=rawRecord as any;if(!validDate(date)||date<s.startedOn||date>localDate()||!r||r.date!==date||!taskList(r.taskSnapshot)||!Array.isArray(r.completedTaskIds)||new Set(r.completedTaskIds).size!==r.completedTaskIds.length||!r.completedTaskIds.every((id:unknown)=>r.taskSnapshot.some((t:Task)=>t.id===id))||r.completionPercent!==percent(r)) throw new Error('Backup contains an invalid daily record.');}
 if(new Set(s.measurements.map((m:any)=>m?.date+':'+m?.kind)).size!==s.measurements.length||!s.measurements.every((m:any)=>m&&validDate(m.date)&&m.date>=s.startedOn&&m.date<=localDate()&&m.kind==='weight'&&m.unit==='kg'&&Number.isFinite(m.value)&&m.value>=1&&m.value<=500)) throw new Error('Backup contains an invalid weight record.');
 for(const [date,r] of entries as [string,DailyRecord][]){if(r.taskSnapshot.some(t=>t.type==='weight'&&r.completedTaskIds.includes(t.id))&&!s.measurements.some((m:Measurement)=>m.date===date))throw new Error('Completed weight task has no measurement.');}
 // Normalize into a fresh, known schema; never retain arbitrary imported fields.
 const cleanTask=(t:Task):Task=>({id:t.id,title:t.title.trim(),period:t.period,daysOfWeek:[...t.daysOfWeek],enabled:t.enabled,type:t.type,...(t.role?{role:t.role}:{})});
 return {schemaVersion:1,startedOn:s.startedOn,tasks:s.tasks.map(cleanTask),days:Object.fromEntries(entries.map(([date,r]:[string,any])=>[date,{date,completedTaskIds:[...r.completedTaskIds],taskSnapshot:r.taskSnapshot.map(cleanTask),completionPercent:r.completionPercent}])),measurements:s.measurements.map((m:Measurement)=>({date:m.date,kind:'weight',value:m.value,unit:'kg'})),settings:{timezone:'Europe/Warsaw',weightUnit:'kg',theme:s.settings.theme}}; }
export function exportBackup(s:State) { return JSON.stringify({app:'DAILY OS',version:1,exportedAt:new Date().toISOString(),data:s},null,2); }
