import {useEffect,useState,type ComponentType,type ReactNode} from 'react';
import {displayDate,localDate,type State} from './model';
import {parsePLN,formatPLN} from './money';
import {saveIdea,deleteIdea,ideaToTask,saveWish,deleteWish,markWishPurchased,saveMeal,deleteMeal,saveMealTemplate,deleteMealTemplate,nutritionTotals,startTimer,pauseTimer,resumeTimer,stopTimer,discardTimer,manualSession,deleteSession,updateSession,activeSeconds,todayTime,weekTime,timeCategories,type Idea,type Wish,type Meal,type MealType,type Macros,type TimeSession} from './modules';

type ModalProps={title:string;onClose:()=>void;children:ReactNode};
type Props={s:State;date:string;busy:boolean;apply:(change:(state:State)=>State)=>Promise<boolean>;Modal:ComponentType<ModalProps>;onBack:()=>void};
export type ModuleName='Ideas'|'Wishlist'|'Nutrition'|'Time Tracking';
const humanDate=(d:string)=>displayDate(d,{day:'numeric',month:'short'});
const duration=(seconds:number)=>{const n=Math.max(0,Math.floor(seconds));return `${Math.floor(n/3600)}h ${Math.floor(n%3600/60)}m`;};
const sub=(text:string)=><p className="small-note">{text}</p>;
function Heading({title,onBack}:{title:string;onBack:()=>void}){return <button className="life-back" onClick={onBack}>← Back to More</button>}
function Blank({text}:{text:string}){return <div className="card life-empty">{text}</div>}
function Danger({busy,onCancel,onDelete,name}:{busy:boolean;onCancel:()=>void;onDelete:()=>void;name:string}){return <><p>Delete “{name}”? This cannot be undone.</p><div className="modal-actions"><button className="soft-button" onClick={onCancel}>Cancel</button><button className="danger-button" disabled={busy} onClick={onDelete}>Delete</button></div></>}
export function ModulesHome({s,onOpen}:{s:State;onOpen:(n:ModuleName)=>void}){
 const tiles:{name:ModuleName;desc:string;value:string}[]=[
 {name:'Ideas',desc:'Capture and develop project ideas',value:`${s.modules?.ideas.length??0} ideas`},
 {name:'Wishlist',desc:'Plan future purchases',value:`${s.modules?.wishlist.filter(x=>!x.purchasedAt).length??0} wanted`},
 {name:'Nutrition',desc:'Meals and optional nutrition notes',value:`${s.modules?.meals.filter(x=>x.date===localDate()).length??0} today`},
 {name:'Time Tracking',desc:'Focus timer and activity log',value:s.modules?.activeTimer?'Timer active':'Start tracking'}];
 return <section className="life-panel"><div className="section-heading"><h2>Your modules</h2><span>Private · Offline</span></div><div className="card module-menu">{tiles.map(t=><button key={t.name} className="module-menu-item" onClick={()=>onOpen(t.name)}><span><b>{t.name}</b><small>{t.desc}</small></span><span className="module-menu-value">{t.value} ›</span></button>)}</div></section>;
}
export function IdeasScreen({s,busy,apply,Modal,onBack}:Props){
 const [form,setForm]=useState<Idea|'new'|null>(null),[deleting,setDeleting]=useState<Idea|null>(null),[error,setError]=useState('');
 const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[category,setCategory]=useState('Projects'),[status,setStatus]=useState<Idea['status']>('New'),[complexity,setComplexity]=useState<Idea['complexity']>('medium'),[potential,setPotential]=useState<Idea['potential']>('medium');
 const begin=(i?:Idea)=>{setForm(i??'new');setError('');setTitle(i?.title??'');setDescription(i?.description??'');setCategory(i?.category??'Projects');setStatus(i?.status??'New');setComplexity(i?.complexity??'medium');setPotential(i?.potential??'medium')};
 const ideas=[...(s.modules?.ideas??[])].sort((a,b)=>Number(a.status==='Archived')-Number(b.status==='Archived')||b.updatedAt.localeCompare(a.updatedAt));
 const submit=async()=>{if(await apply(st=>saveIdea(st,{title,description,category,status,complexity,potential},typeof form==='object'&&form?form.id:undefined)))setForm(null);};
 return <><Heading title="Ideas" onBack={onBack}/><div className="section-heading outside"><h2>Ideas</h2><button className="soft-button" disabled={busy} onClick={()=>begin()}>+ Add idea</button></div>{sub('A quiet place for new projects, research and plans. Turn an idea into a one-time task when you are ready.')}
 {ideas.length?<div className="card module-list">{ideas.map(i=><div className="module-entry" key={i.id}><button className="module-entry-main" onClick={()=>begin(i)}><b>{i.title}</b><small>{i.category} · {i.status} · potential {i.potential}</small>{i.description&&<span>{i.description.length>130?i.description.slice(0,130)+'…':i.description}</span>}</button><button className="module-mini" disabled={busy} onClick={()=>void apply(st=>ideaToTask(st,i.id))}>{i.linkedActionId&&s.life?.actions.some(a=>a.id===i.linkedActionId)?'Task linked':'+ Task'}</button></div>)}</div>:<Blank text="No ideas yet. Start by recording one."/>}
 {form&&<Modal title={form==='new'?'New idea':'Edit idea'} onClose={()=>setForm(null)}><form className="life-form" onSubmit={e=>{e.preventDefault();void submit()}}><label>Title<input required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Description<textarea rows={4} maxLength={3000} value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Category<input required maxLength={60} value={category} onChange={e=>setCategory(e.target.value)}/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value as Idea['status'])}>{(['New','Researching','Active','Completed','Archived'] as const).map(x=><option key={x}>{x}</option>)}</select></label><label>Complexity<select value={complexity} onChange={e=>setComplexity(e.target.value as Idea['complexity'])}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><label>Potential<select value={potential} onChange={e=>setPotential(e.target.value as Idea['potential'])}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label>{error&&<p role="alert">{error}</p>}<button className="primary-button" disabled={busy||!title.trim()||!category.trim()}>Save idea</button>{form!=='new'&&<button className="text-danger" type="button" onClick={()=>{setDeleting(form);setForm(null)}}>Delete idea</button>}</form></Modal>}
 {deleting&&<Modal title="Delete idea" onClose={()=>setDeleting(null)}><Danger name={deleting.title} busy={busy} onCancel={()=>setDeleting(null)} onDelete={()=>void apply(st=>deleteIdea(st,deleting.id)).then(ok=>{if(ok)setDeleting(null)})}/></Modal>}
 </>;
}
export function WishlistScreen({s,date,busy,apply,Modal,onBack}:Props){
 const [form,setForm]=useState<Wish|'new'|null>(null),[deleting,setDeleting]=useState<Wish|null>(null),[buy,setBuy]=useState<Wish|null>(null);
 const [title,setTitle]=useState(''),[price,setPrice]=useState(''),[url,setUrl]=useState(''),[category,setCategory]=useState('Shopping'),[priority,setPriority]=useState<Wish['priority']>('medium'),[note,setNote]=useState('');
 const [validationError,setValidationError]=useState('');
 const begin=(i?:Wish)=>{setForm(i??'new');setValidationError('');setTitle(i?.title??'');setPrice(i?.priceMinor===null||i===undefined?'':(i.priceMinor/100).toFixed(2));setUrl(i?.url??'');setCategory(i?.category??'Shopping');setPriority(i?.priority??'medium');setNote(i?.note??'');};
 const save=async()=>{try{const minor=price.trim()?parsePLN(price,true):null;if(await apply(st=>saveWish(st,{title,priceMinor:minor,url,category,priority,note},typeof form==='object'&&form?form.id:undefined)))setForm(null)}catch(e){setValidationError(e instanceof Error?e.message:'Invalid price.')}};
 const ordered=[...(s.modules?.wishlist??[])].sort((a,b)=>Number(!!a.purchasedAt)-Number(!!b.purchasedAt)||({high:0,medium:1,low:2}[a.priority]-{high:0,medium:1,low:2}[b.priority]));
 return <><Heading title="Wishlist" onBack={onBack}/><div className="section-heading outside"><h2>Wishlist</h2><button className="soft-button" onClick={()=>begin()}>+ Add item</button></div>{sub('Wishlist is separate from Money. Creating an expense is always optional and requires confirmation.')}
 {ordered.length?<div className="card module-list">{ordered.map(i=><div className="module-entry" key={i.id}><button className="module-entry-main" onClick={()=>begin(i)}><b>{i.title}{i.purchasedAt?' ✓':''}</b><small>{i.priceMinor===null?'Price not set':formatPLN(i.priceMinor)} · {i.priority} · {i.category}</small>{i.note&&<span>{i.note}</span>}</button><div className="module-entry-actions">{i.url&&<a className="module-mini" href={i.url} target="_blank" rel="noreferrer noopener">Link ↗</a>}{!i.purchasedAt&&<button className="module-mini" onClick={()=>setBuy(i)}>Bought</button>}</div></div>)}</div>:<Blank text="Wishlist is empty. Add something you may buy later."/>}
 {form&&<Modal title={form==='new'?'New wishlist item':'Edit wishlist item'} onClose={()=>setForm(null)}><form className="life-form" onSubmit={e=>{e.preventDefault();void save()}}><label>Item<input maxLength={120} required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Estimated price (zł, optional)<input inputMode="decimal" placeholder="24,90" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Product link (optional)<input type="url" maxLength={1200} placeholder="https://…" value={url} onChange={e=>setUrl(e.target.value)}/></label><label>Category<input maxLength={60} required value={category} onChange={e=>setCategory(e.target.value)}/></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value as Wish['priority'])}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><label>Notes<textarea rows={2} maxLength={1200} value={note} onChange={e=>setNote(e.target.value)}/></label>{validationError&&<p className="form-error" role="alert">{validationError}</p>}<button className="primary-button" disabled={busy||!title.trim()||!category.trim()}>Save item</button>{form!=='new'&&<button type="button" className="text-danger" onClick={()=>{setDeleting(form);setForm(null)}}>Delete item</button>}</form></Modal>}
 {buy&&<Modal title="Mark purchased" onClose={()=>setBuy(null)}><p>{buy.title}{buy.priceMinor!==null?` · ${formatPLN(buy.priceMinor)}`:''}</p><p className="small-note">Choose whether to record a Shopping expense in Money. Only one expense can be created for this purchase.</p><div className="module-confirm-actions"><button disabled={busy} className="soft-button" onClick={()=>void apply(st=>markWishPurchased(st,buy.id,false,date)).then(ok=>{if(ok)setBuy(null)})}>Mark only</button><button disabled={busy||!buy.priceMinor} className="primary-button" onClick={()=>void apply(st=>markWishPurchased(st,buy.id,true,date)).then(ok=>{if(ok)setBuy(null)})}>Mark + Money expense</button><button className="soft-button" onClick={()=>setBuy(null)}>Cancel</button></div></Modal>}
 {deleting&&<Modal title="Delete wishlist item" onClose={()=>setDeleting(null)}><Danger name={deleting.title} busy={busy} onCancel={()=>setDeleting(null)} onDelete={()=>void apply(st=>deleteWish(st,deleting.id)).then(ok=>{if(ok)setDeleting(null)})}/><p className="small-note">Deleting a wishlist item never removes an existing Money transaction.</p></Modal>}
 </>;
}
export function NutritionScreen({s,date,busy,apply,Modal,onBack}:Props){
 const [form,setForm]=useState<Meal|'new'|null>(null),[deleting,setDeleting]=useState<Meal|null>(null),[selected,setSelected]=useState(date);
 const [name,setName]=useState(''),[mealDate,setMealDate]=useState(date),[type,setType]=useState<MealType>('Lunch'),[portion,setPortion]=useState('');
 const [calories,setCalories]=useState(''),[protein,setProtein]=useState(''),[fat,setFat]=useState(''),[carbs,setCarbs]=useState(''),[inputError,setInputError]=useState('');
 const begin=(m?:Meal)=>{setForm(m??'new');setInputError('');setName(m?.name??'');setMealDate(m?.date??selected);setType(m?.type??'Lunch');setPortion(m?.portion??'');setCalories(m?.macros.calories?.toString()??'');setProtein(m?.macros.protein?.toString()??'');setFat(m?.macros.fat?.toString()??'');setCarbs(m?.macros.carbs?.toString()??'')};
 const parse=(s:string)=>{if(!s.trim())return undefined;const normalized=s.trim().replace(',','.');if(!/^\d{1,6}(\.\d)?$/.test(normalized))throw new Error('Nutrition values must be nonnegative numbers with at most one decimal place.');return Number(normalized)};
 const submit=async()=>{try{const macros:Macros={};for(const [key,text] of [['calories',calories],['protein',protein],['fat',fat],['carbs',carbs]] as const){const v=parse(text);if(v!==undefined)macros[key]=v;}if(await apply(st=>saveMeal(st,{date:mealDate,type,name,portion,macros},typeof form==='object'&&form?form.id:undefined)))setForm(null)}catch(e){setInputError(e instanceof Error?e.message:'Invalid nutrition data.')}};
 const items=(s.modules?.meals??[]).filter(x=>x.date===selected).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));const totals=nutritionTotals(s,selected);
 return <><Heading title="Nutrition" onBack={onBack}/><div className="section-heading outside"><h2>Nutrition</h2><button className="soft-button" onClick={()=>begin()}>+ Log meal</button></div>{sub('A food journal, not a diet plan. All nutrition figures are optional and manually entered; no calorie target or automated food estimates.')}
 <div className="card module-section"><label className="module-inline-label">Day <input type="date" aria-label="Nutrition date" min="2000-01-01" max="2100-12-31" value={selected} onChange={e=>setSelected(e.target.value)}/></label><div className="module-stats"><span>Meals <b>{totals.count}</b></span>{(['calories','protein','fat','carbs'] as const).map(k=><span key={k}>{k==='calories'?'Energy':k[0].toUpperCase()+k.slice(1)} <b>{totals.totals[k]===undefined?'—':`${totals.totals[k]} ${k==='calories'?'kcal':'g'}`}</b></span>)}</div>{totals.incomplete&&sub('Some entries have no nutrition values. Totals include only known, manually entered values.')}</div>
 {items.length?<div className="card module-list">{items.map(m=><div className="module-entry" key={m.id}><button className="module-entry-main" onClick={()=>begin(m)}><b>{m.name}</b><small>{m.type}{m.portion?` · ${m.portion}`:''}</small><span>{Object.keys(m.macros).length?`${m.macros.calories??'—'} kcal · P ${m.macros.protein??'—'} · F ${m.macros.fat??'—'} · C ${m.macros.carbs??'—'}`:'Nutrition not entered'}</span></button><button className="module-mini" disabled={busy} onClick={()=>void apply(st=>saveMealTemplate(st,m.id))}>Save dish</button></div>)}</div>:<Blank text="No meals recorded for this date."/>}
 {!!s.modules?.mealTemplates.length&&<section className="life-panel"><h2>Saved dishes</h2><div className="card module-list">{s.modules.mealTemplates.map(t=><div className="module-entry" key={t.id}><div className="module-entry-main"><b>{t.name}</b><small>{t.portion||'Serving not specified'}</small></div><div className="module-entry-actions"><button className="module-mini" disabled={busy} onClick={()=>void apply(st=>saveMeal(st,{date:selected,type:'Lunch',name:t.name,portion:t.portion,macros:{...t.macros}}))}>+ Log</button><button className="module-mini" disabled={busy} aria-label={`Remove saved dish ${t.name}`} onClick={()=>void apply(st=>deleteMealTemplate(st,t.id))}>×</button></div></div>)}</div></section>}
 {form&&<Modal title={form==='new'?'Log meal':'Edit meal'} onClose={()=>setForm(null)}><form className="life-form" onSubmit={e=>{e.preventDefault();void submit()}}><label>Food / dish<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>Meal<select value={type} onChange={e=>setType(e.target.value as MealType)}>{(['Breakfast','Lunch','Dinner','Snack'] as const).map(t=><option key={t}>{t}</option>)}</select></label><label>Date<input type="date" min="2000-01-01" max="2100-12-31" required value={mealDate} onChange={e=>setMealDate(e.target.value)}/></label><label>Portion / amount (optional)<input maxLength={100} placeholder="e.g. one bowl" value={portion} onChange={e=>setPortion(e.target.value)}/></label><p className="small-note">Optional nutrition information, if known (per logged portion)</p><div className="module-macro-inputs"><label>Calories<input inputMode="decimal" placeholder="kcal" value={calories} onChange={e=>setCalories(e.target.value)}/></label><label>Protein, g<input inputMode="decimal" value={protein} onChange={e=>setProtein(e.target.value)}/></label><label>Fat, g<input inputMode="decimal" value={fat} onChange={e=>setFat(e.target.value)}/></label><label>Carbs, g<input inputMode="decimal" value={carbs} onChange={e=>setCarbs(e.target.value)}/></label></div>{inputError&&<p className="form-error" role="alert">{inputError}</p>}<button className="primary-button" disabled={busy||!name.trim()}>Save meal</button>{form!=='new'&&<button type="button" className="text-danger" onClick={()=>{setDeleting(form);setForm(null)}}>Delete meal</button>}</form></Modal>}
 {deleting&&<Modal title="Delete meal" onClose={()=>setDeleting(null)}><Danger name={deleting.name} busy={busy} onCancel={()=>setDeleting(null)} onDelete={()=>void apply(st=>deleteMeal(st,deleting.id)).then(ok=>{if(ok)setDeleting(null)})}/></Modal>}
 </>;
}
export function TimeScreen({s,date,busy,apply,Modal,onBack}:Props){
 const [tick,setTick]=useState(Date.now());const [category,setCategory]=useState('Study'),[note,setNote]=useState(''),[manual,setManual]=useState(false),[edit,setEdit]=useState<TimeSession|null>(null),[remove,setRemove]=useState<TimeSession|null>(null),[discard,setDiscard]=useState(false),[when,setWhen]=useState(date),[minutes,setMinutes]=useState('30');const [err,setErr]=useState('');
 useEffect(()=>{const id=window.setInterval(()=>setTick(Date.now()),1000);return()=>clearInterval(id)},[]);
 const active=s.modules?.activeTimer;const seconds=active?activeSeconds(active,new Date(tick).toISOString()):0;const today=todayTime(s,date);const weekly=weekTime(s,date);const recent=[...(s.modules?.sessions??[])].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,30);
 const saveEntry=async()=>{const v=Number(minutes.replace(',','.'));if(!Number.isFinite(v)||v<=0||v>10080){setErr('Enter a positive duration of at most 168 hours.');return;}const fn=(st:State)=>edit?updateSession(st,edit.id,{category,note,...(!edit.segments?.length?{minutes:v}:{})}):manualSession(st,when,category,v,note);if(await apply(fn)){setManual(false);setEdit(null);setErr('')}};
 const openEdit=(item:TimeSession)=>{setEdit(item);setManual(true);setCategory(item.category);setNote(item.note);setWhen(item.date);setMinutes(String(Math.max(1,item.seconds/60)));setErr('')};
 return <><Heading title="Time Tracking" onBack={onBack}/><div className="section-heading outside"><h2>Time Tracking</h2><button className="soft-button" onClick={()=>{setEdit(null);setManual(true);setCategory('Study');setNote('');setWhen(date);setMinutes('30');setErr('')}}>+ Manual entry</button></div>{sub('A timer for your activities. It uses saved timestamps, so leaving the PWA and reopening it does not reset a running session.')}
 <section className="card module-section"><div className="module-timer-time" aria-live="off">{active?duration(seconds):'0h 0m'}</div>{active?<><p className="small-note">{active.category}{active.note?` · ${active.note}`:''} · {active.runningSince?'Running':'Paused'}</p><div className="module-timer-buttons"><button className="soft-button" disabled={busy} onClick={()=>void apply(st=>active.runningSince?pauseTimer(st):resumeTimer(st))}>{active.runningSince?'Pause':'Resume'}</button><button className="primary-button" disabled={busy} onClick={()=>void apply(st=>stopTimer(st))}>Stop & save</button></div><button className="text-danger" disabled={busy} onClick={()=>setDiscard(true)}>Discard timer</button></>:<div className="life-form"><label>Activity<select aria-label="Time category" value={category} onChange={e=>setCategory(e.target.value)}>{timeCategories.map(c=><option key={c}>{c}</option>)}</select></label><label>Note (optional)<input maxLength={300} value={note} onChange={e=>setNote(e.target.value)}/></label><button className="primary-button" disabled={busy} onClick={()=>void apply(st=>startTimer(st,category,note))}>Start timer</button></div>}</section>
 <section className="card module-section"><div className="section-heading"><h2>Recorded time</h2></div><div className="module-stats"><span>Today <b>{duration(today.seconds)}</b></span><span>This week <b>{duration(weekly.seconds)}</b></span></div><div className="module-time-cats">{Object.entries(weekly.categories).sort((a,b)=>b[1]-a[1]).map(([cat,sec])=><div key={cat}><span>{cat}</span><b>{duration(sec)}</b></div>)}</div></section>
 <section className="life-panel"><h2>Recent sessions</h2>{recent.length?<div className="card module-list">{recent.map(i=><div className="module-entry" key={i.id}><button className="module-entry-main" onClick={()=>openEdit(i)}><b>{i.category} · {duration(i.seconds)}</b><small>{humanDate(i.date)} · {i.segments?.length?'Timer':'Manual'}</small>{i.note&&<span>{i.note}</span>}</button><button className="module-mini" aria-label={`Delete session ${i.category} ${i.date}`} onClick={()=>setRemove(i)}>×</button></div>)}</div>:<Blank text="No time entries yet."/>}</section>
 {manual&&<Modal title={edit?'Edit session':'Manual time entry'} onClose={()=>{setManual(false);setEdit(null)}}><form className="life-form" onSubmit={e=>{e.preventDefault();void saveEntry()}}><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{[...new Set([...timeCategories,...(edit?[edit.category]:[])])].map(x=><option key={x}>{x}</option>)}</select></label>{!edit&&<label>Date<input type="date" min="2000-01-01" max="2100-12-31" value={when} onChange={e=>setWhen(e.target.value)} required/></label>}<label>Duration (minutes)<input type="number" inputMode="decimal" min="1" max="10080" step="1" value={minutes} disabled={!!edit?.segments?.length} onChange={e=>setMinutes(e.target.value)}/></label>{!!edit?.segments?.length&&sub('Recorded timer durations are not editable; the measured segments are preserved.')}<label>Note<input maxLength={300} value={note} onChange={e=>setNote(e.target.value)}/></label>{err&&<p className="form-error" role="alert">{err}</p>}<button className="primary-button" disabled={busy}>Save session</button></form></Modal>}
 {remove&&<Modal title="Delete time entry" onClose={()=>setRemove(null)}><Danger name={remove.category} busy={busy} onCancel={()=>setRemove(null)} onDelete={()=>void apply(st=>deleteSession(st,remove.id)).then(ok=>{if(ok)setRemove(null)})}/></Modal>}
 {discard&&<Modal title="Discard current timer?" onClose={()=>setDiscard(false)}><p>Unsaved time from this timer will be lost.</p><div className="modal-actions"><button className="soft-button" onClick={()=>setDiscard(false)}>Cancel</button><button className="danger-button" disabled={busy} onClick={()=>void apply(discardTimer).then(ok=>{if(ok)setDiscard(false)})}>Discard</button></div></Modal>}
 </>;
}
export function ModulePage({name,...props}:Props&{name:ModuleName}){switch(name){case 'Ideas':return <IdeasScreen {...props}/>;case 'Wishlist':return <WishlistScreen {...props}/>;case 'Nutrition':return <NutritionScreen {...props}/>;case 'Time Tracking':return <TimeScreen {...props}/>;}}
