import {useState,type ComponentType,type ReactNode} from 'react';
import {displayDate,shiftDate,type State} from './model';
import {categories,deleteTransaction,emptyMoney,moneyStats,moneyText,parseAmount,putTransaction,setStartingBalance,type Transaction} from './money';
export interface UndoAction {message:string;restore:(state:State)=>State}
export function MoneyScreen({s,date,busy,apply,onUndo,Dialog}:{s:State;date:string;busy:boolean;apply:(change:(s:State)=>State)=>Promise<boolean>;onUndo:(undo:UndoAction)=>void;Dialog:ComponentType<{title:string;onClose:()=>void;children:ReactNode}>}){
 const m=s.money??emptyMoney(),stats=moneyStats(s,date);
 const [balanceOpen,setBalanceOpen]=useState(false),[balance,setBalance]=useState(''),[editing,setEditing]=useState<Transaction>(),[kind,setKind]=useState<'income'|'expense'>(),[selected,setSelected]=useState<Transaction>(),[deleting,setDeleting]=useState<Transaction>();
 const [amount,setAmount]=useState(''),[title,setTitle]=useState(''),[category,setCategory]=useState('Food'),[transactionDate,setTransactionDate]=useState(date),[formError,setFormError]=useState('');
 function open(type:'income'|'expense',t?:Transaction){setEditing(t);setKind(type);setAmount(t?(t.amountMinor/100).toFixed(2):'');setTitle(t?.title??'');setCategory(t?.category??(type==='expense'?'Food':'Income'));setTransactionDate(t?.date??date);setFormError('');setSelected(undefined);}
 async function save(){try{const amountMinor=parseAmount(amount),now=new Date().toISOString();if(transactionDate>date)throw new Error('Choose today or an earlier date.');const t:Transaction={id:editing?.id??crypto.randomUUID(),type:kind!,amountMinor,title:title.trim(),category,date:transactionDate,createdAt:editing?.createdAt??now,updatedAt:now};if(await apply(state=>putTransaction(state,t))){setKind(undefined);if(!editing)onUndo({message:kind==='expense'?'Expense added':'Income added',restore:state=>deleteTransaction(state,t.id)});}}catch(e){setFormError(e instanceof Error?e.message:'Check the transaction.');}}
 const dates=[...new Set(m.transactions.map(t=>t.date))].sort().reverse();
 return <><section className="card money-balance"><p className="eyebrow">BALANCE</p>{m.startingBalanceMinor===null?<><h2>Start with your balance</h2><p className="small-note">Then record money coming in and going out.</p><button className="primary-button" onClick={()=>{setBalance('');setBalanceOpen(true);setFormError('');}}>Set starting balance</button></>:<><strong data-testid="money-balance">{moneyText(stats.balance)}</strong><button className="money-base" onClick={()=>{setBalance((m.startingBalanceMinor!/100).toFixed(2));setBalanceOpen(true);setFormError('');}}>Starting balance · {moneyText(m.startingBalanceMinor)}</button></>}</section><div className="money-actions"><button className="primary-button" disabled={m.startingBalanceMinor===null} onClick={()=>open('income')}>+ Income</button><button className="soft-button" disabled={m.startingBalanceMinor===null} onClick={()=>open('expense')}>− Expense</button></div><section className="card money-month"><div className="section-heading"><h2>This month</h2><span>{displayDate(date,{month:'long'})}</span></div><div className="money-totals"><div><span>Income</span><b>+{moneyText(stats.income)}</b></div><div><span>Spent</span><b>−{moneyText(stats.spent)}</b></div><div><span>Net</span><b>{stats.net>=0?'+':''}{moneyText(stats.net)}</b></div></div>{stats.top&&<><p className="small-note">Top spending category · {stats.top.category} · {moneyText(stats.top.amountMinor)}</p><div className="category-breakdown">{stats.breakdown.map(item=><div key={item.category}><div><span>{item.category}</span><b>{moneyText(item.amountMinor)}</b></div><span className="category-bar"><i style={{width:`${item.amountMinor/stats.top!.amountMinor*100}%`}}/></span></div>)}</div></>}</section><div className="section-heading outside"><h2>Transactions</h2><span>{m.transactions.length} entries</span></div>{dates.length?dates.map(d=><section key={d} className="money-history"><h2>{d===date?'Today':d===shiftDate(date,-1)?'Yesterday':displayDate(d,{month:'long',day:'numeric',year:'numeric'})}</h2><div className="card">{m.transactions.filter(t=>t.date===d).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(t=><button className="transaction-row" key={t.id} onClick={()=>setSelected(t)}><span><b>{t.title}</b><small>{t.category}</small></span><strong>{t.type==='income'?'+':'−'}{moneyText(t.amountMinor)}</strong></button>)}</div></section>):<div className="card empty"><p>No transactions yet.<br/>A quick entry is all you need.</p></div>}
 {balanceOpen&&<Dialog title="Set starting balance" onClose={()=>setBalanceOpen(false)}><form className="editor" onSubmit={async e=>{e.preventDefault();try{const minor=parseAmount(balance,true);if(await apply(state=>setStartingBalance(state,minor)))setBalanceOpen(false);}catch(e){setFormError((e as Error).message);}}}><label>Starting balance (zł)<input aria-label="Starting balance in PLN" inputMode="decimal" value={balance} onChange={e=>setBalance(e.target.value)} required placeholder="1000.00"/></label><p className="small-note">The base before all recorded transactions. Zero is allowed.</p>{formError&&<p role="alert" className="form-error">{formError}</p>}<button className="primary-button" disabled={busy}>Save balance</button></form></Dialog>}
 {kind&&<Dialog title={editing?'Edit transaction':kind==='income'?'Add income':'Add expense'} onClose={()=>setKind(undefined)}><form className="editor" onSubmit={e=>{e.preventDefault();void save();}}><label>Amount (zł)<input aria-label="Amount in PLN" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} required placeholder="24.90"/></label><label>{kind==='expense'?'What for?':'From what?'}<input aria-label="Transaction title" value={title} maxLength={100} onChange={e=>setTitle(e.target.value)} required placeholder={kind==='expense'?'Lunch':'Sold headphones'}/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Date<input type="date" value={transactionDate} min="2000-01-01" max={date} onChange={e=>setTransactionDate(e.target.value)} required/></label>{formError&&<p role="alert" className="form-error">{formError}</p>}<button className="primary-button" disabled={busy}>Save transaction</button></form></Dialog>}
 {selected&&<Dialog title={selected.title} onClose={()=>setSelected(undefined)}><p className="detail-weight">{selected.type==='income'?'+':'−'}{moneyText(selected.amountMinor)}</p><p>{selected.category} · {displayDate(selected.date)}</p><div className="modal-actions"><button className="soft-button" onClick={()=>open(selected.type,selected)}>Edit transaction</button><button className="danger-button" onClick={()=>{setDeleting(selected);setSelected(undefined);}}>Delete transaction</button></div></Dialog>}
 {deleting&&<Dialog title="Delete transaction?" onClose={()=>setDeleting(undefined)}><p>{deleting.title} · {moneyText(deleting.amountMinor)}</p><p>Your balance and monthly totals will update. You can undo this for a few seconds.</p><div className="modal-actions"><button className="soft-button" onClick={()=>setDeleting(undefined)}>Cancel</button><button className="danger-button" disabled={busy} onClick={async()=>{const removed=deleting;if(await apply(state=>deleteTransaction(state,removed.id))){setDeleting(undefined);onUndo({message:'Transaction deleted',restore:state=>{if(state.money?.transactions.some(t=>t.id===removed.id))throw new Error('Transaction already exists.');return putTransaction(state,removed);}});}}}>Delete</button></div></Dialog>}
 </>;
}
