import {useState,type ComponentType,type ReactNode} from 'react';
import {displayDate,shiftDate,type State} from './model';
import {expenseCategories,emptyMoney,parsePLN,formatPLN,moneyStats,setStartingBalance,saveTransaction,deleteTransaction,type Transaction} from './money';
type ModalProps={title:string;onClose:()=>void;children:ReactNode};
type Change=(s:State)=>State;
export function MoneyScreen({s,date,busy,apply,Modal,onUndo}:{s:State;date:string;busy:boolean;apply:(fn:Change)=>Promise<boolean>;Modal:ComponentType<ModalProps>;onUndo:(change:Change,message:string)=>void}){
 const money=s.money??emptyMoney(),stats=moneyStats(money,date);
 const [opening,setOpening]=useState(false),[starting,setStarting]=useState(''),[form,setForm]=useState<{type:'income'|'expense';transaction?:Transaction}>(),[deleting,setDeleting]=useState<Transaction>();
 const [amount,setAmount]=useState(''),[title,setTitle]=useState(''),[category,setCategory]=useState(''),[when,setWhen]=useState(date),[error,setError]=useState('');
 const begin=(type:'income'|'expense',t?:Transaction)=>{setForm({type,transaction:t});setAmount(t?(t.amountMinor/100).toFixed(2):'');setTitle(t?.title??'');setCategory(t?.category??(type==='income'?'Income':'Food'));setWhen(t?.date??date);setError('');};
 const dates=[...new Set(money.transactions.map(t=>t.date))].sort().reverse();
 return <>
 <section className="card money-balance" aria-label="Balance"><p className="eyebrow">BALANCE</p><strong data-testid="money-balance">{formatPLN(stats.balance)}</strong><button className="money-base" onClick={()=>{setStarting(((money.startingBalanceMinor??0)/100).toFixed(2));setError('');setOpening(true)}}>{money.startingBalanceMinor===null?'Set starting balance':`Starting balance · ${formatPLN(money.startingBalanceMinor)}`}</button>{money.startingBalanceMinor===null&&<p className="small-note">Set your starting cash amount. Income and expenses update it automatically.</p>}</section>
 <MoneySummary s={s} date={date}/>
 <div className="money-actions"><button className="primary-button" disabled={busy} onClick={()=>begin('income')}>+ Income</button><button className="soft-button" disabled={busy} onClick={()=>begin('expense')}>− Expense</button></div>
 {stats.top&&<section className="card money-breakdown"><h2>Spending this month</h2><p className="small-note">Top spending category · <b>{stats.top[0]}</b> · {formatPLN(stats.top[1])}</p>{stats.breakdown.map(([name,minor])=><div className="category-row" key={name}><div><span>{name}</span><b>{formatPLN(minor)}</b></div><div className="category-bar"><span style={{width:`${minor/stats.spent*100}%`}}/></div></div>)}</section>}
 <div className="section-heading outside"><h2>Transactions</h2><span>{money.transactions.length}</span></div>
 {!dates.length?<section className="card empty"><h2>A clear start.</h2><p>Record what came in and what you spent.</p></section>:dates.map(d=><section className="money-day" key={d}><h3>{d===date?'TODAY':d===shiftDate(date,-1)?'YESTERDAY':displayDate(d,{month:'long',day:'numeric',year:'numeric'})}</h3><div className="card">{money.transactions.filter(t=>t.date===d).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||a.id.localeCompare(b.id)).map(t=><div className="transaction" key={t.id}><button className="transaction-main" aria-label={`Edit ${t.title}`} onClick={()=>begin(t.type,t)}><strong className={t.type==='income'?'income':''}>{t.type==='income'?'+':'−'}{formatPLN(t.amountMinor)}</strong><b>{t.title}</b><span>{t.category}</span></button><button className="transaction-delete" aria-label={`Delete ${t.title}`} onClick={()=>setDeleting(t)}>Delete</button></div>)}</div></section>)}
 {opening&&<Modal title="Set starting balance" onClose={()=>setOpening(false)}><form className="editor" onSubmit={async e=>{e.preventDefault();try{const minor=parsePLN(starting,true);if(await apply(v=>setStartingBalance(v,minor)))setOpening(false)}catch(e){setError((e as Error).message)}}}><label>Starting balance (zł)<input inputMode="decimal" value={starting} onChange={e=>setStarting(e.target.value)} required maxLength={12}/></label><p className="small-note">This is the base before all recorded transactions. Changing it does not remove transactions.</p>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary-button" disabled={busy}>Save starting balance</button></form></Modal>}
 {form&&<Modal title={form.transaction?'Edit transaction':form.type==='income'?'Add income':'Add expense'} onClose={()=>setForm(undefined)}><form className="editor" onSubmit={async e=>{e.preventDefault();try{const now=new Date().toISOString(),t:Transaction={id:form.transaction?.id??crypto.randomUUID(),type:form.type,amountMinor:parsePLN(amount),title:title.trim(),category:category.trim(),date:when,createdAt:form.transaction?.createdAt??now,updatedAt:now};if(!t.title||!t.category)throw new Error('Enter a title and category.');if(await apply(v=>saveTransaction(v,t))){if(!form.transaction)onUndo(v=>{const current=v.money?.transactions.find(x=>x.id===t.id);if(current&&JSON.stringify(current)!==JSON.stringify(t))throw new Error('This transaction changed after it was added.');return deleteTransaction(v,t.id)},form.type==='income'?'Income added':'Expense added');setForm(undefined)}}catch(e){setError((e as Error).message)}}}><label>Amount (zł)<input inputMode="decimal" maxLength={12} value={amount} onChange={e=>setAmount(e.target.value)} placeholder="24.90" required/></label><label>{form.type==='income'?'From what?':'What for?'}<input maxLength={120} value={title} onChange={e=>setTitle(e.target.value)} placeholder={form.type==='income'?'Sold headphones':'Lunch'} required/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{[...new Set([...(form.type==='income'?['Income']:expenseCategories),category])].filter(Boolean).map(c=><option key={c}>{c}</option>)}</select></label><label>Date<input type="date" min="2000-01-01" max="2100-12-31" value={when} onChange={e=>setWhen(e.target.value)} required/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary-button" disabled={busy}>Save transaction</button></form></Modal>}
 {deleting&&<Modal title="Delete transaction?" onClose={()=>setDeleting(undefined)}><p>Delete “{deleting.title}” · {formatPLN(deleting.amountMinor)}?</p><div className="modal-actions"><button className="soft-button" onClick={()=>setDeleting(undefined)}>Cancel</button><button className="danger-button" disabled={busy} onClick={async()=>{const t=deleting;if(await apply(v=>deleteTransaction(v,t.id))){onUndo(v=>{if(v.money?.transactions.some(x=>x.id===t.id))throw new Error('Transaction already exists.');return saveTransaction(v,t)},'Transaction deleted');setDeleting(undefined)}}}>Delete transaction</button></div></Modal>}
 </>;
}
export function MoneySummary({s,date}:{s:State;date:string}){const stats=moneyStats(s.money,date);return <section className="card money-summary" aria-label="Money this month"><h2>This month</h2><div className="money-summary-grid"><div><span>Income</span><b data-testid="month-income">+{formatPLN(stats.income)}</b></div><div><span>Spent</span><b data-testid="month-spent">−{formatPLN(stats.spent)}</b></div><div><span>Net</span><b data-testid="month-net">{stats.net>=0?'+':'−'}{formatPLN(Math.abs(stats.net))}</b></div></div></section>}
