import type { State } from './model';
export interface Transaction { id:string; type:'income'|'expense'; amountMinor:number; title:string; category:string; date:string; createdAt:string; updatedAt:string }
export interface Money { currency:'PLN'; startingBalanceMinor:number|null; transactions:Transaction[] }
export const expenseCategories=['Food','Transport','Gym','Shopping','Entertainment','Subscriptions','School','Health','Other'] as const;
export const MAX_MINOR=10_000_000_000;
export const emptyMoney=():Money=>({currency:'PLN',startingBalanceMinor:null,transactions:[]});
export function parsePLN(input:string,allowZero=false):number {
 const value=input.trim();if(!/^\d{1,9}([.,]\d{1,2})?$/.test(value))throw new Error('Enter a PLN amount with up to two decimal places.');
 const [whole,fraction='']=value.replace(',','.').split('.');const minor=Number(whole)*100+Number(fraction.padEnd(2,'0'));
 if(!Number.isSafeInteger(minor)||minor>(MAX_MINOR)||minor<(allowZero?0:1))throw new Error('Amount must be greater than zero and at most 100 000 000 zł.');return minor;
}
export const formatPLN=(minor:number)=>new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(minor/100)+' zł';
const validDate=(v:unknown):v is string=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&v>='2000-01-01'&&v<='2100-12-31'&&Number.isFinite(Date.parse(v+'T12:00:00Z'))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v;
const stamp=(v:unknown):v is string=>typeof v==='string'&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString()===v;
export function validTransaction(t:any):t is Transaction {return !!t&&typeof t.id==='string'&&/^[a-zA-Z0-9_-]{1,80}$/.test(t.id)&&['income','expense'].includes(t.type)&&Number.isSafeInteger(t.amountMinor)&&t.amountMinor>0&&t.amountMinor<=MAX_MINOR&&typeof t.title==='string'&&t.title.trim().length>0&&t.title.length<=120&&typeof t.category==='string'&&t.category.trim().length>0&&t.category.length<=40&&validDate(t.date)&&stamp(t.createdAt)&&stamp(t.updatedAt)&&t.updatedAt>=t.createdAt;}
export function validateMoney(value:unknown):Money {const m=value as Money;if(!m||m.currency!=='PLN'||(m.startingBalanceMinor!==null&&(!Number.isSafeInteger(m.startingBalanceMinor)||m.startingBalanceMinor<0||m.startingBalanceMinor>MAX_MINOR))||!Array.isArray(m.transactions)||m.transactions.length>100000||!m.transactions.every(validTransaction)||new Set(m.transactions.map(t=>t.id)).size!==m.transactions.length)throw new Error('Backup contains invalid Money data.');return {currency:'PLN',startingBalanceMinor:m.startingBalanceMinor,transactions:m.transactions.map(t=>({id:t.id,type:t.type,amountMinor:t.amountMinor,title:t.title.trim(),category:t.category.trim(),date:t.date,createdAt:t.createdAt,updatedAt:t.updatedAt}))};}
export function setStartingBalance(s:State,minor:number){if(!Number.isSafeInteger(minor)||minor<0||minor>MAX_MINOR)throw new Error('Invalid starting balance.');(s.money??=emptyMoney()).startingBalanceMinor=minor;return s;}
export function saveTransaction(s:State,t:Transaction){if(!validTransaction(t))throw new Error('Check the transaction amount, title, category and date.');const m=s.money??=emptyMoney();const existing=m.transactions.find(x=>x.id===t.id);if(existing&&existing.createdAt!==t.createdAt)throw new Error('Transaction creation time cannot change.');if(!existing&&m.transactions.length>=100000)throw new Error('Transaction limit reached.');m.transactions=m.transactions.filter(x=>x.id!==t.id);m.transactions.push({...t,title:t.title.trim(),category:t.category.trim()});return s;}
export function deleteTransaction(s:State,id:string){if(s.money)s.money.transactions=s.money.transactions.filter(t=>t.id!==id);return s;}
export function moneyStats(m:Money=emptyMoney(),date:string){let balance=m.startingBalanceMinor??0,income=0,spent=0;const categories:Record<string,number>=Object.create(null);for(const t of m.transactions){balance+=t.type==='income'?t.amountMinor:-t.amountMinor;if(t.date.slice(0,7)===date.slice(0,7)){if(t.type==='income')income+=t.amountMinor;else{spent+=t.amountMinor;categories[t.category]=(categories[t.category]??0)+t.amountMinor;}}}const breakdown=Object.entries(categories).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));return {balance,income,spent,net:income-spent,breakdown,top:breakdown[0]};}
