import type { State } from './model';
export const categories=['Food','Transport','Gym','Shopping','Entertainment','Subscriptions','School','Health','Other','Income'] as const;
export interface Transaction {id:string;type:'income'|'expense';amountMinor:number;title:string;category:string;date:string;createdAt:string;updatedAt:string}
export interface Money {currency:'PLN';startingBalanceMinor:number|null;transactions:Transaction[]}
export const emptyMoney=():Money=>({currency:'PLN',startingBalanceMinor:null,transactions:[]});
export const MAX_MINOR=10_000_000_000;
export function parseAmount(text:string,allowZero=false):number {const match=/^(\d{1,9})(?:[.,](\d{1,2}))?$/.exec(text.trim());if(!match)throw new Error('Enter an amount with up to two decimal places.');const value=Number(match[1])*100+Number((match[2]??'').padEnd(2,'0'));if(!Number.isSafeInteger(value)||value>MAX_MINOR||value<(allowZero?0:1))throw new Error('Enter an amount between 0.01 and 100,000,000 zł.');return value;}
export function moneyText(minor:number){return new Intl.NumberFormat('pl-PL',{minimumFractionDigits:2,maximumFractionDigits:2}).format(minor/100)+' zł';}
const dateValid=(date:unknown)=>typeof date==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(date)&&date>='2000-01-01'&&date<='2100-12-31'&&Number.isFinite(Date.parse(date+'T12:00:00Z'))&&new Date(date+'T12:00:00Z').toISOString().slice(0,10)===date;
const stamp=(v:unknown)=>typeof v==='string'&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString()===v;
export function validTransaction(t:unknown):t is Transaction {const v=t as Transaction;return !!v&&typeof v.id==='string'&&/^[a-zA-Z0-9_-]{1,80}$/.test(v.id)&&['income','expense'].includes(v.type)&&Number.isSafeInteger(v.amountMinor)&&v.amountMinor>0&&v.amountMinor<=MAX_MINOR&&typeof v.title==='string'&&!!v.title.trim()&&v.title.length<=100&&categories.includes(v.category as typeof categories[number])&&dateValid(v.date)&&stamp(v.createdAt)&&stamp(v.updatedAt)&&v.updatedAt>=v.createdAt;}
export function validMoney(v:unknown):v is Money {const m=v as Money;return !!m&&m.currency==='PLN'&&(m.startingBalanceMinor===null||(Number.isSafeInteger(m.startingBalanceMinor)&&m.startingBalanceMinor>=0&&m.startingBalanceMinor<=MAX_MINOR))&&Array.isArray(m.transactions)&&m.transactions.length<=100000&&m.transactions.every(validTransaction)&&new Set(m.transactions.map(t=>t.id)).size===m.transactions.length;}
export function setStartingBalance(s:State,minor:number){if(!Number.isSafeInteger(minor)||minor<0||minor>MAX_MINOR)throw new Error('Invalid starting balance.');(s.money??=emptyMoney()).startingBalanceMinor=minor;return s;}
export function putTransaction(s:State,t:Transaction){if(!validTransaction(t))throw new Error('Check transaction amount, title, category and date.');const m=s.money??=emptyMoney(),i=m.transactions.findIndex(x=>x.id===t.id);if(i<0){if(m.transactions.length>=100000)throw new Error('Transaction history is full. Export a backup.');m.transactions.push({...t,title:t.title.trim()});}else m.transactions[i]={...t,title:t.title.trim(),createdAt:m.transactions[i].createdAt};return s;}
export function deleteTransaction(s:State,id:string){const m=s.money??=emptyMoney();m.transactions=m.transactions.filter(t=>t.id!==id);return s;}
export function moneyStats(s:State,date:string){const m=s.money??emptyMoney();const sum=(ts:Transaction[],type:Transaction['type'])=>ts.filter(t=>t.type===type).reduce((n,t)=>n+t.amountMinor,0);const all=m.transactions,month=all.filter(t=>t.date.slice(0,7)===date.slice(0,7));const income=sum(month,'income'),spent=sum(month,'expense');const totals=new Map<string,number>();for(const t of month)if(t.type==='expense')totals.set(t.category,(totals.get(t.category)??0)+t.amountMinor);const breakdown=[...totals].map(([category,amountMinor])=>({category,amountMinor})).sort((a,b)=>b.amountMinor-a.amountMinor||a.category.localeCompare(b.category));return {balance:(m.startingBalanceMinor??0)+sum(all,'income')-sum(all,'expense'),income,spent,net:income-spent,breakdown,top:breakdown[0]};}
