import {useEffect,useRef,useState} from 'react';
import type {Quote} from './quotes';
import {visualPath} from './quotes';
export function Opening({quote,visualId,onClose}:{quote:Quote;visualId:string;onClose:()=>void}){
 const [fallback,setFallback]=useState(false),[closing,setClosing]=useState(false),button=useRef<HTMLButtonElement>(null),close=useRef(onClose);close.current=onClose;
 useEffect(()=>{if(!closing)return;const timer=setTimeout(()=>close.current(),matchMedia('(prefers-reduced-motion: reduce)').matches?0:180);return()=>clearTimeout(timer);},[closing]);
 useEffect(()=>{const previous=document.activeElement as HTMLElement;button.current?.focus();const timer=setTimeout(()=>setClosing(true),matchMedia('(prefers-reduced-motion: reduce)').matches?100:2620);const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setClosing(true);};document.addEventListener('keydown',key);const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{clearTimeout(timer);document.removeEventListener('keydown',key);document.body.style.overflow=overflow;previous?.focus();};},[]);
 return <div className={closing?'opening closing':'opening'} role="dialog" aria-modal="true" aria-label="Daily opening" data-testid="opening"><img className="opening-image" src={visualPath(fallback?'garden-1':visualId)} alt="Original thematic artwork" onError={()=>setFallback(true)} fetchPriority="high"/><div className="opening-shade"/><button ref={button} className="opening-content" onKeyDown={e=>{if(e.key==='Tab')e.preventDefault();}} onClick={()=>setClosing(true)} aria-label="Tap to continue"><span className="opening-brand">DAILY OS</span><span className="opening-quote" data-testid="opening-quote">{quote.type==='quote'?`“${quote.text}”`:quote.text}</span><span className="opening-author">{quote.type==='reflection'?'Inspired by ':''}{quote.author}</span>{quote.universe&&<span className="opening-universe">{quote.universe}</span>}<span className="opening-label">{quote.type==='reflection'?'Original reflection':'Daily quote'}</span><span className="opening-timer"/><span className="opening-skip">Tap to continue</span></button></div>;
}
