// Original editorial writing. Names describe thematic inspiration, never literal attribution.
export const jjkGroups:[string,string,string[]][]=[
['Satoru Gojo','gojo',[
'Confidence should sharpen your actions, not make them careless.','Mastery leaves enough attention to notice others.','Make room for people who can surpass you.','A strong foundation gives freedom somewhere to stand.','Learn the rule before deciding where it bends.','Do not confuse being admired with being understood.','Your advantages still need deliberate practice.','The strongest person in a room can still listen.','Give talent a routine worthy of it.','Being capable does not make every burden yours.','Teach the method, not dependence on your presence.','Take your work seriously without losing your humour.','A good challenge reveals what comfort hides.','Protect your attention as carefully as your strength.','Power gains purpose when someone benefits from it.','Leave space between a first reaction and a decision.','You can be confident and admit uncertainty.','Choose standards that survive without an audience.','An easy win is not always useful practice.','Precision matters even when you have an advantage.','Your limits deserve investigation, not denial.','Build allies who can stand on their own.','Make the next generation stronger than your reputation.','Rest is part of keeping your edge.','A clear mind can see more than a loud one.','Let curiosity stay alive after success.','You do not need to prove yourself in every conversation.','A playful approach can coexist with careful preparation.','Use your freedom to choose worthwhile responsibilities.','Being exceptional does not remove the need for friends.','Know when restraint is the stronger choice.','A setback is information your confidence must absorb.','Work on the weakness your talent usually conceals.','Leave a difficult task with a clearer understanding.','Distance can help you see a problem; connection helps you solve it.','Measure your growth beyond the last victory.','Keep promises that nobody can force you to keep.','Protect the future, not only your position.']],
['Toji Fushiguro','toji',[
'Preparation can compensate for an uneven starting point.','Notice the opening before spending your effort.','Keep your tools simple and well understood.','Conditioning is built before the decisive moment.','A quiet approach can save unnecessary effort.','Work with the body you have, then improve it.','Do not mistake surprise for a repeatable strategy.','An efficient movement begins with observation.']],
['Ryomen Sukuna','sukuna',[
'Understand your capabilities without worshipping them.','A clear objective makes wasted effort visible.','Study the technique that disrupts your assumptions.','Control starts with knowing what you can actually do.','Ambition needs a precise next action.','Respect a difficult problem enough to examine it.','A larger goal still depends on exact execution.','Make judgement stronger than the urge to dominate.']],
['Yuji Itadori','yuji',[
'Care becomes real through the next helpful action.','Keep your kindness when progress becomes difficult.','You can learn without losing your concern for others.','A mistake deserves responsibility and a better attempt.','Ask for support before a burden becomes isolation.','Showing up again can be a meaningful kind of courage.','Protect the person behind the performance.','Let grief remind you of what deserves care.']],
['Megumi Fushiguro','megumi',[
'Choose where your limited energy can do the most good.','A careful plan needs room for an unexpected turn.','Your potential is not a substitute for an attempt.','Use what you know before chasing a perfect solution.','A quiet commitment can guide a difficult choice.','Recognise when caution has become avoidance.','Ask what resources you have overlooked.','Give yourself permission to take a useful risk.']],
['Yuta Okkotsu','yuta',[
'Gentleness and capability can grow together.','Trust develops when you act reliably under pressure.','Accept help without treating it as a weakness.','A bond can be a reason to become more capable.','Uncertainty does not prevent a careful first step.','Learn to carry responsibility without carrying everything alone.','Your past does not decide every next action.','Keep practising the skill you once feared.']],
['Maki Zenin','maki',[
'An unfair starting point does not invalidate your effort.','Build evidence where others offer only judgement.','Your preparation belongs to you.','Let physical practice teach patience as well as strength.','Choose a standard beyond the expectations placed on you.','Do not let rejection become your only motivation.','Progress can be quiet before it becomes visible.','Make your next repetition honest.']],
['Kento Nanami','nanami',[
'Boundaries help you keep doing good work.','A clear routine reduces unnecessary decisions.','Professional care shows in the details nobody praises.','Finish the responsibility you can reasonably carry.','Rest should not require a crisis to become legitimate.','Do the practical thing before the dramatic thing.','Separate a difficult task from a difficult identity.','Be reliable without becoming endlessly available.']],
['Suguru Geto','geto',[
'Examine a belief before it hardens into contempt.','Isolation can distort a problem that conversation might clarify.','A worthy purpose must remain open to correction.','Do not let one painful experience explain every person.','Question the cost of the path you have chosen.','Keep compassion wider than your own group.','A conviction deserves scrutiny as much as loyalty.','Notice when certainty begins to silence curiosity.']],
['Aoi Todo','todo',[
'Know what matters to you before borrowing another standard.','Practice adapting, not merely repeating.','A good partner helps you notice your blind spots.','Bring enthusiasm to work that still needs precision.','Learn from the person beside you.','A quick adjustment can matter more than a louder effort.','Take your preferences seriously without making them universal.','Keep attention in the present exchange.']],
['Kinji Hakari','hakari',[
'Enthusiasm is useful when the downside is understood.','A risk becomes clearer when you name what you could lose.','Momentum needs recovery as well as commitment.','Luck is no reason to skip preparation.','Choose excitement that leaves tomorrow possible.','A streak does not change the need for judgement.','Know when the next attempt needs a different method.','Keep your energy grounded in a workable plan.']],
['Hajime Kashimo','kashimo',[
'A worthy challenge tests the skill you care about.','Intensity becomes useful when it has direction.','Seek information beyond the thrill of competition.','Prepare for the effort a serious attempt requires.','Do not spend every reserve on proving a point.','A precise question can focus a powerful effort.','A stronger rival can reveal a better training problem.','Let the pursuit deepen your understanding.']],
['Choso','choso',[
'Loyalty is expressed in consistent care.','Protecting someone includes hearing what they need.','Let responsibility grow beyond a narrow circle.','A family bond still needs honest communication.','You can revise your understanding without abandoning your care.','Stay present when support becomes inconvenient.','Ask who is carrying the burden with you.','Make affection visible in a practical action.']],
['Nobara Kugisaki','nobara',[
'Self-respect can survive another person’s disapproval.','Keep a place for the things that make you yourself.','Confidence does not need everyone’s agreement.','Your standards should include how you treat yourself.','Take up space with care and intention.','A firm boundary can be a kind decision.','Choose company that leaves room for your individuality.','You can enjoy beauty and still value capability.']],
['Mahito','mahito',[
'Curiosity needs ethical boundaries.','A capacity to change does not justify every change.','Notice when experimentation forgets the person affected.','Understanding another person is not permission to manipulate them.','Novelty is not evidence of improvement.','A useful question includes who bears the cost.','Treat vulnerability as a responsibility, not an opportunity.','Change deserves a standard beyond possibility.']],
['Kenjaku','kenjaku',[
'A long plan must still justify its immediate cost.','Strategy without accountability can become harm.','Review whether your experiment answers a meaningful question.','Do not let complexity hide a weak assumption.','Patience is useful only in service of a sound purpose.','An impressive scheme can still have a false premise.','Consider the people missing from your model.','An outcome is not a complete account of its consequences.']]
];
// Six distinct additional reflections per author. All explicitly marked original.
export const realGroups:[string,string,string[]][]=[
['Marcus Aurelius','philosophy',['Attend to the duty nearest you.','An interruption can become a practice in patience.','Choose conduct you can respect at night.','Let praise pass without choosing your direction.','Meet inconvenience without adding contempt.','Use today before judging its imperfections.']],
['Seneca','philosophy',['Examine what your calendar actually values.','Prepare for change without rehearsing every fear.','Enough is easier to recognise with a clear purpose.','Give friendship time rather than leftover attention.','Learn which urgency is borrowed.','A pause can return ownership of an hour.']],
['Epictetus','philosophy',['Separate your choice from the result.','An impression is an invitation to examine.','Train your response in ordinary frustrations.','Do not outsource your standards to applause.','Begin where your influence is real.','Name the judgement attached to the event.']],
['Friedrich Nietzsche','ambition',['Create a reason to endure repetition.','Question the comfort of inherited certainty.','Turn resistance into a question about growth.','Examine whether your ambition is truly yours.','Build beyond the identity of being opposed.','A difficult ascent still needs a chosen destination.']],
['Miyamoto Musashi','focus',['Observe rhythm before choosing speed.','Practise the fundamentals beyond familiarity.','A useful stance allows adjustment.','Know your tool through patient repetition.','See the whole situation around the detail.','Do not confuse tension with readiness.']],
['Bruce Lee','growth',['Keep the method open to experience.','Remove effort that serves no purpose.','Learn what changes when conditions change.','A familiar movement can reveal a new detail.','Let practice test your preferred explanation.','Adapt without abandoning your foundation.']],
['Muhammad Ali','sport',['Prepare when the crowd is absent.','Courage still needs conditioning.','Own the effort before predicting the outcome.','Make your confidence answerable to practice.','Keep dignity beyond winning and losing.','Bring conviction to the next round of work.']],
['Kobe Bryant','discipline',['Make the ordinary drill worth doing.','Study the mistake after the emotion settles.','A serious goal needs protected practice time.','Treat recovery as preparation for tomorrow.','Notice the quality inside each repetition.','Seek feedback on the work you avoid.']],
['Michael Jordan','sport',['A missed attempt still gives information.','Prepare for the role your team needs.','Compete with the problem before the person.','Keep learning after a successful performance.','Trust becomes visible in shared work.','Practise the moment before relying on instinct.']],
['Arnold Schwarzenegger','strength',['Give your plan a place in the week.','Choose effort you can repeat consistently.','Build strength through manageable progression.','Track the work rather than only the mirror.','Recovery protects the training you have earned.','A larger ambition begins with a completed session.']],
['David Goggins','resilience',['Distinguish discomfort from a warning signal.','Make your commitment concrete enough to practise.','A hard day can include a sensible adjustment.','Face the task you keep postponing.','Keep an honest record of your effort.','Persistence needs a body that can recover.']],
['Carl Sagan','science',['A surprising claim deserves a careful test.','Wonder grows with accurate understanding.','Keep scale in mind when certainty feels large.','Ask what evidence would change your belief.','Curiosity can coexist with humility.','Protect the conditions that make learning possible.']],
['Richard Feynman','science',['Explain the step you think is obvious.','A label is not yet an understanding.','Check whether the result survives another method.','Make room for a useful failed experiment.','Separate what you observed from what you inferred.','Look for the assumption hiding in the calculation.']],
['Albert Einstein','science',['Imagine freely and check carefully.','Reframe the question before adding complexity.','A simple model still has a domain of validity.','Ask which measurement could distinguish explanations.','Give a stubborn problem time away from the desk.','Follow curiosity past the familiar wording.']],
['Steve Jobs','leadership',['Choose the detail that improves actual use.','Simplicity requires deciding what to leave out.','Follow interest with the patience to build.','A setback can sharpen your priorities.','Care for the experience beyond the first impression.','Make the purpose clearer than the feature list.']],
['Ada Lovelace','science',['Ask what a tool could express beyond its first use.','Imagination benefits from precise structure.','A pattern becomes useful when its rules are clear.','Translate an idea into steps you can inspect.','Explore connections between different kinds of knowledge.','Check the mechanism behind the elegant possibility.']],
['Marie Curie','resilience',['Keep the observation more important than the expectation.','Patient work can make a hidden pattern visible.','Ask for evidence where reputation offers certainty.','Protect health while pursuing a demanding question.','Let precision guide the next experiment.','A result deserves careful recording.']],
['Charles Darwin','science',['Notice the detail that does not fit.','Collect observations before defending a theory.','Give an explanation time to face alternatives.','Small differences can matter over long periods.','Keep a record of objections to your view.','Ask how the environment changes the result.']],
['Isaac Newton','science',['Define the quantity before doing the calculation.','A powerful rule still needs its conditions.','Look for a relation beneath separate observations.','Check the units before trusting the answer.','An exact question can simplify a large problem.','Trace a result back through every assumption.']],
['Nikola Tesla','focus',['Give imagination a disciplined test.','A vivid idea still needs a working mechanism.','Understand the constraints around an invention.','Record the detail before it escapes attention.','A failed design can improve the next drawing.','Make ingenuity serve a real need.']],
['Leonardo da Vinci','growth',['Draw what you notice before naming it.','A close observation can open a new question.','Study the connection between form and function.','Let different disciplines inform each other.','Curiosity needs time with ordinary objects.','A sketch can reveal a gap in understanding.']],
['Galileo Galilei','science',['Compare the explanation with what can be measured.','Improve the instrument as well as the theory.','An unexpected observation deserves another look.','Distinguish a repeated result from a persuasive story.','Ask what the measurement actually represents.','Keep evidence open to independent checking.']],
['Jane Goodall','science',['Patient attention reveals behaviour haste misses.','Observe before imposing a familiar story.','Care can motivate careful knowledge.','Consider the living subject behind the data.','Let a long observation challenge a quick assumption.','Understanding creates practical responsibilities.']],
['Rachel Carson','science',['Look beyond the immediate effect.','A useful intervention needs a wider view of consequences.','Notice what a system depends on quietly.','Ask who inherits the cost of today’s choice.','Preserve uncertainty where the evidence is incomplete.','Care for the conditions that support life.']],
['Hannah Arendt','philosophy',['Think through the action you are asked to repeat.','Responsibility does not disappear inside a routine.','Make room for a different person’s perspective.','A public claim deserves private examination.','Judge the specific case with attention.','Habit is not a complete reason to continue.']],
['Simone de Beauvoir','philosophy',['Freedom gains meaning through actual choices.','Notice the expectations shaping your options.','Treat another person as a chooser too.','A possibility needs conditions that make it real.','Examine the role you have accepted automatically.','Build independence without denying interdependence.']],
['Baruch Spinoza','philosophy',['Understanding an emotion can widen your choices.','Look for causes beyond the first impression.','A clear explanation can soften needless anger.','Ask what increases your ability to act well.','Knowledge grows through connected understanding.','Examine the desire before obeying it.']],
['Aristotle','growth',['A repeated action gives a value its shape.','Choose practice that builds the quality you want.','Notice the appropriate amount for the situation.','Good judgement needs experience and reflection.','A worthy aim still needs practical means.','Learn to do the thing by doing it carefully.']],
['Plato','philosophy',['Question the appearance before accepting the conclusion.','Ask what your definition leaves out.','A conversation can expose an unnoticed contradiction.','Distinguish persuasion from understanding.','Let a better question interrupt a quick answer.','Examine the standard behind your judgement.']],
['Socrates','philosophy',['Explain what you mean by the key word.','An unanswered question can be useful progress.','Listen for the assumption inside your certainty.','Invite an objection you can learn from.','A good conversation changes the question.','Knowledge begins with an honest limit.']],
['Confucius','leadership',['Respect becomes visible in small reliable actions.','Practise the consideration you expect from others.','Learning needs reflection to become judgement.','Set an example within your actual responsibility.','Keep a promise small enough to honour.','Improve the conduct closest to you.']],
['Laozi','philosophy',['Leave room for what cannot be forced.','A quiet adjustment may work better than pressure.','Notice when adding effort adds friction.','Simplicity can reveal the next useful step.','Listen before trying to fill the silence.','Let the situation inform your pace.']],
['Zhuangzi','philosophy',['Consider the view from another position.','A familiar distinction may hide other possibilities.','Let curiosity loosen a rigid judgement.','Ask whether the struggle serves your purpose.','A change of scale can change the question.','Allow uncertainty to keep thought flexible.']],
['Viktor Frankl','resilience',['Look for a responsibility that gives today meaning.','A difficult feeling need not choose every action.','Meaning can begin with a concrete act of care.','Keep a reason beyond immediate comfort.','Notice the choice that remains available.','Do not demand happiness before acting with purpose.']],
['James Baldwin','philosophy',['Name what needs to be faced clearly.','An honest account can make change possible.','Listen to experience beyond your own.','Care and difficult truth can belong together.','Examine the story you use to excuse a habit.','Make room for the person behind the category.']],
['Maya Angelou','resilience',['Let dignity guide a difficult response.','Offer care in a form someone can receive.','Your voice deserves thoughtful use.','A painful experience need not erase possibility.','Recognise the effort behind another person’s composure.','Keep room for joy during serious work.']],
['Toni Morrison','growth',['Attend to the voice missing from the story.','A meaningful detail can change the whole picture.','Make room for complexity in another person.','Memory deserves careful interpretation.','Write the thought you keep circling.','Language can clarify what silence leaves tangled.']],
['George Orwell','focus',['Choose a concrete word for a concrete thing.','Ask whether your sentence hides the actor.','Clarity helps a claim become accountable.','Notice the distance between the slogan and the action.','Check the fact before repeating the familiar story.','A precise description can resist convenient confusion.']],
['Ralph Waldo Emerson','growth',['Give experience a chance to inform your judgement.','Try the idea outside its comfortable wording.','Notice what captures your independent attention.','A thoughtful choice may differ from the crowd.','Let practice develop confidence in your own view.','Remain willing to revise what you once defended.']],
['Henry David Thoreau','focus',['Look at where your hours actually go.','Leave a little room for unhurried attention.','A simpler commitment may be easier to honour.','A walk can return perspective to a problem.','Choose enough before accumulating more.','Test a priority through your ordinary day.']],
['Theodore Roosevelt','leadership',['Contribute where participation is possible.','Courage needs a task rather than a performance.','Use the resources within reach.','Accept feedback as part of taking responsibility.','A worthwhile effort can include an imperfect result.','Put conviction into useful work.']],
['Nelson Mandela','leadership',['Patience can support a clear commitment.','Listen without giving up your standards.','Build trust through the promise you keep today.','A long goal needs durable relationships.','Look for progress that others can share.','Dignity belongs in the method as well as the outcome.']],
['Abraham Lincoln','leadership',['Understand the disagreement before replying.','A measured response can preserve a useful conversation.','Keep the larger responsibility in view.','Invite advice that tests your preferred plan.','Choose words that leave room for cooperation.','Make decisions with the limits of your knowledge visible.']],
['Eleanor Roosevelt','leadership',['Take a small step toward the responsibility you avoid.','Make your concern practical.','Consider who cannot easily speak in the room.','A useful contribution does not require perfect confidence.','Protect dignity in ordinary interactions.','Build courage through manageable action.']],
['Winston Churchill','resilience',['Name the next workable step under pressure.','Preparation makes a difficult decision less blind.','Keep communication clear when events move quickly.','Review the plan when facts change.','Persistence needs attention to the actual situation.','A steady response can outlast a dramatic gesture.']],
['Serena Williams','sport',['Train the skill beneath the visible result.','Confidence can return through consistent preparation.','Give recovery a place beside intensity.','Stay with the next point of attention.','Adjust to the opponent without losing your plan.','A difficult session still deserves honest evaluation.']],
['Usain Bolt','sport',['Relaxation can be part of precise speed.','Practise the start before imagining the finish.','Let timing refine raw effort.','A brief performance rests on long preparation.','Keep attention on the phase you are in.','Protect the recovery that quality work requires.']],
['Eliud Kipchoge','discipline',['Respect the rhythm of sustainable work.','A calm pace can carry a demanding purpose.','Let consistency make progress visible over time.','Train with others without borrowing their limits.','Give the ordinary session complete attention.','Recovery belongs in a durable routine.']],
['Simone Biles','sport',['Listen when safety needs your attention.','Precision deserves practice at an appropriate difficulty.','Your worth exceeds a single performance.','Build confidence through skills you can repeat.','A responsible pause can protect future progress.','Trust should grow from reliable preparation.']],
['Roger Federer','sport',['Make room for ease inside careful execution.','Study the transition between separate skills.','Choose placement before unnecessary force.','Adapt to the day’s conditions.','A graceful movement still needs repetition.','Keep respect in the contest.']],
['Florence Nightingale','leadership',['Measure whether your care changes the outcome.','A clear record can reveal a preventable problem.','Improve the environment around the individual task.','Make an observation useful to the next person.','Practical compassion pays attention to details.','Ask which condition makes good work difficult.']],
['Katherine Johnson','science',['Check the calculation that others depend on.','Confidence grows from a result you can verify.','Explain the path as well as the answer.','Precision is a practical form of care.','Break the large problem into inspectable steps.','A second method can reveal a hidden error.']],
['Grace Hopper','science',['Understand the system before excusing its limits.','Make a difficult tool easier to use.','A practical demonstration can clarify an argument.','Question a routine that no longer serves its purpose.','Translate complexity into a useful explanation.','Document the detail the next person will need.']],
['Alan Turing','science',['State the problem so another mind can inspect it.','A precise model reveals what it cannot decide.','Look for the structure behind repeated operations.','Test the boundary case.','A surprising pattern deserves a careful definition.','Understanding grows when a process becomes explicit.']],
['Bertrand Russell','philosophy',['Keep confidence proportionate to the evidence.','Enjoy a question without rushing to certainty.','A clear argument still needs sound premises.','Distinguish an appealing conclusion from a supported one.','Invite the example that could challenge your rule.','Let curiosity remain larger than your allegiance.']]
];
export const fictionalGroups:[string,string,string[]][]=[
['Guts','dark',['Keep moving without denying the weight you carry.','Let support reach the part you hide.','A difficult past does not remove every future choice.','Rest can protect the reason you continue.','Choose a purpose beyond surviving the next struggle.','Strength can include trusting a companion.']],
['Thorfinn','warrior',['Make a different response possible through practice.','A new purpose needs ordinary work.','Peace can require more skill than retaliation.','Take responsibility without becoming only your mistakes.','Choose the future your habits are building.','Learn to protect without feeding a conflict.']],
['Vegeta','sport',['A rival can reveal a useful training target.','Keep refining after a breakthrough.','Pride becomes useful when it accepts feedback.','Master the weakness you would rather conceal.','A stronger standard still needs recovery.','Growth need not erase the people beside you.']],
['Rock Lee','sport',['Give patient repetition a meaningful direction.','An honest baseline helps you see progress.','Effort works better with technique.','Build what your starting advantages did not provide.','Respect the body carrying your ambition.','Keep learning from the next attempt.']],
['Uncle Iroh','philosophy',['Leave room for kindness in a difficult day.','A pause can make the next choice wiser.','Care for the person beyond their useful role.','Find a small pleasure without abandoning purpose.','Offer guidance that leaves room for choice.','A different path can begin with listening.']],
['Aragorn','leadership',['Carry responsibility without demanding recognition.','Lead where your example can be seen.','A long journey needs care for companions.','Let courage include sound judgement.','Keep a promise when its cost becomes real.','Prepare to serve the role you hope to hold.']],
['Spock','science',['Check whether the evidence supports your confidence.','Emotion is information worth understanding.','A logical argument depends on its premises.','Compare alternatives before choosing a conclusion.','State the uncertainty beside the result.','A clear question can improve a difficult decision.']]
];
